version: "3.8"

networks:
  kafka-net:
    driver: bridge
  bft:
    driver: bridge

services:
  #First kafka replica
  zookeeper-1-1:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper-1-2:2888:3888,zookeeper-1-3:2888:3888,zookeeper-1-4:2888:3888
  zookeeper-1-2:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper-1-1:2888:3888,0.0.0.0:2888:3888,zookeeper-1-3:2888:3888,zookeeper-1-4:2888:3888
  zookeeper-1-3:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper-1-1:2888:3888,zookeeper-1-2:2888:3888,0.0.0.0:2888:3888,zookeeper-1-4:2888:3888
  zookeeper-1-4:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=4
      - ZOO_SERVERS=zookeeper-1-1:2888:3888,zookeeper-1-2:2888:3888,zookeeper-1-3:2888:3888,0.0.0.0:2888:3888
  kafka_1_1:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-net
    depends_on:
      - "zookeeper-1-1"
      - "zookeeper-1-2"
      - "zookeeper-1-3"
      - "zookeeper-1-4"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_1:9092
  kafka_1_2:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-net
    depends_on:
      - "zookeeper-1-1"
      - "zookeeper-1-2"
      - "zookeeper-1-3"
      - "zookeeper-1-4"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_2:9092
  kafka_1_3:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-net
    depends_on:
      - "zookeeper-1-1"
      - "zookeeper-1-2"
      - "zookeeper-1-3"
      - "zookeeper-1-4"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_3:9092
  kafka_1_4:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-net
    depends_on:
      - "zookeeper-1-1"
      - "zookeeper-1-2"
      - "zookeeper-1-3"
      - "zookeeper-1-4"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=4
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_4:9092

  #Second kafka replica
  zookeeper-2-1:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper-2-2:2888:3888,zookeeper-2-3:2888:3888,zookeeper-2-4:2888:3888
  zookeeper-2-2:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper-2-1:2888:3888,0.0.0.0:2888:3888,zookeeper-2-3:2888:3888,zookeeper-2-4:2888:3888
  zookeeper-2-3:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper-2-1:2888:3888,zookeeper-2-2:2888:3888,0.0.0.0:2888:3888,zookeeper-2-4:2888:3888
  zookeeper-2-4:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=4
      - ZOO_SERVERS=zookeeper-2-1:2888:3888,zookeeper-2-2:2888:3888,zookeeper-2-3:2888:3888,0.0.0.0:2888:3888
  kafka_2_1:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-net
    depends_on:
      - "zookeeper-2-1"
      - "zookeeper-2-2"
      - "zookeeper-2-3"
      - "zookeeper-2-4"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-2-1:2181,zookeeper-2-2:2181,zookeeper-2-3:2181,zookeeper-2-4:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_2_1:9092
  kafka_2_2:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-net
    depends_on:
      - "zookeeper-2-1"
      - "zookeeper-2-2"
      - "zookeeper-2-3"
      - "zookeeper-2-4"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-2-1:2181,zookeeper-2-2:2181,zookeeper-2-3:2181,zookeeper-2-4:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_2_2:9092
  kafka_2_3:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-net
    depends_on:
      - "zookeeper-2-1"
      - "zookeeper-2-2"
      - "zookeeper-2-3"
      - "zookeeper-2-4"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-2-1:2181,zookeeper-2-2:2181,zookeeper-2-3:2181,zookeeper-2-4:2181
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_2_3:9092
  kafka_2_4:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-net
    depends_on:
      - "zookeeper-2-1"
      - "zookeeper-2-2"
      - "zookeeper-2-3"
      - "zookeeper-2-4"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-2-1:2181,zookeeper-2-2:2181,zookeeper-2-3:2181,zookeeper-2-4:2181
      - KAFKA_BROKER_ID=4
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_2_4:9092

  #Bft service replicas
  bft-1:
    image: "${DOCKERHUB_USERNAME}/kabis-service-replica:latest"
    networks:
      - bft
    environment:
      - ID=0
  bft-2:
    image: "${DOCKERHUB_USERNAME}/kabis-service-replica:latest"
    networks:
      - bft
    environment:
      - ID=1
  bft-3:
    image: "${DOCKERHUB_USERNAME}/kabis-service-replica:latest"
    networks:
      - bft
    environment:
      - ID=2
  bft-4:
    image: "${DOCKERHUB_USERNAME}/kabis-service-replica:latest"
    networks:
      - bft
    environment:
      - ID=3

  #Clients
  sender-1:
    image: "${DOCKERHUB_USERNAME}/kabis-sender:latest"
    networks:
      - kafka-net
      - bft
    depends_on:
      - "kafka_1_1"
      - "kafka_1_2"
      - "kafka_1_3"
      - "kafka_1_4"
      - "kafka_2_1"
      - "kafka_2_2"
      - "kafka_2_3"
      - "kafka_2_4"
      - "bft-1"
      - "bft-2"
      - "bft-3"
      - "bft-4"
    environment:
      - ID=1001
      - NUM_OPERATIONS=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
      - NUM_VALIDATED=$VALIDATED
    volumes:
      - ./results/sender-1:/usr/kabis/result
  sender-2:
    image: "${DOCKERHUB_USERNAME}/kabis-sender:latest"
    networks:
      - kafka-net
      - bft
    depends_on:
      - "kafka_1_1"
      - "kafka_1_2"
      - "kafka_1_3"
      - "kafka_1_4"
      - "kafka_2_1"
      - "kafka_2_2"
      - "kafka_2_3"
      - "kafka_2_4"
      - "bft-1"
      - "bft-2"
      - "bft-3"
      - "bft-4"
    environment:
      - ID=1002
      - NUM_OPERATIONS=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
      - NUM_VALIDATED=$VALIDATED
    volumes:
      - ./results/sender-2:/usr/kabis/result
  sender-3:
    image: "${DOCKERHUB_USERNAME}/kabis-sender:latest"
    networks:
      - kafka-net
      - bft
    depends_on:
      - "kafka_1_1"
      - "kafka_1_2"
      - "kafka_1_3"
      - "kafka_1_4"
      - "kafka_2_1"
      - "kafka_2_2"
      - "kafka_2_3"
      - "kafka_2_4"
      - "bft-1"
      - "bft-2"
      - "bft-3"
      - "bft-4"
    environment:
      - ID=1003
      - NUM_OPERATIONS=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
      - NUM_VALIDATED=$VALIDATED
    volumes:
      - ./results/sender-3:/usr/kabis/result
  receiver-1:
    image: "${DOCKERHUB_USERNAME}/kabis-receiver:latest"
    networks:
      - kafka-net
      - bft
    depends_on:
      - "kafka_1_1"
      - "kafka_1_2"
      - "kafka_1_3"
      - "kafka_1_4"
      - "kafka_2_1"
      - "kafka_2_2"
      - "kafka_2_3"
      - "kafka_2_4"
      - "bft-1"
      - "bft-2"
      - "bft-3"
      - "bft-4"
    environment:
      - ID=1004
      - NUM_SENDERS=3
      - OPS_PER_SENDER=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
      - NUM_VALIDATED=$VALIDATED
    volumes:
      - ./results/receiver-1:/usr/kabis/result
