version: "3.8"

networks:
  kafka-network:
    name: kafka_benchmarks
    external: true
    driver: overlay

services:
  #First kafka replica
  zookeeper-1-4:
    image: "bitnami/zookeeper:latest"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=4
      - ZOO_SERVERS=zookeeper-1-1:2888:3888,zookeeper-1-2:2888:3888,zookeeper-1-3:2888:3888,0.0.0.0:2888:3888

  kafka_1_4:
    image: "bitnami/kafka:latest"
    depends_on:
      - "zookeeper-1-4"
    networks:
      - kafka-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=4
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_4:9092

  #Clients
  receiver-1:
    image: "${DOCKERHUB_USERNAME}/kafka-receiver:latest"
    networks:
      - kafka-network
    depends_on:
      - "kafka_1_4"
    environment:
      - ID=1004
      - OPS_PER_SENDER=$SENDER_OPS
      - NUM_SENDERS=3
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/receiver-1:/usr/kabis/result
