version: "3.8"

networks:
  kafka-network:
    name: kafka_benchmarks
    external: true
    driver: overlay

services:
  zookeeper-1-3:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper-1-1:2888:3888,zookeeper-1-2:2888:3888,0.0.0.0:2888:3888,zookeeper-1-4:2888:3888
  zookeeper-1-4:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=4
      - ZOO_SERVERS=zookeeper-1-1:2888:3888,zookeeper-1-2:2888:3888,zookeeper-1-3:2888:3888,0.0.0.0:2888:3888

  kafka_1_3:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-network
    depends_on:
      - "zookeeper-1-3"
      - "zookeeper-1-4"
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_3:9092
  kafka_1_4:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-network
    depends_on:
      - "zookeeper-1-3"
      - "zookeeper-1-4"
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=4
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_4:9092

  #Clients
  art-estate:
    image: "${DOCKERHUB_USERNAME}/art-estate:latest"
    networks:
      - kafka-network
    depends_on:
      - "init-kafka"
    environment:
      - CLIENT_ID=2
      - NUM_EXHIBITIONS=$NUM_EXHIBITIONS
      - NUM_TRUE_ALARMS=$NUM_TRUE_ALARMS
      - NUM_FALSE_ALARMS=$NUM_FALSE_ALARMS
      - NUM_UNCAUGHT_BREACHES=$NUM_UNCAUGHT_BREACHES
    volumes:
      - ./results/art-estate:/usr/kabis/result
  ensure:
    image: "${DOCKERHUB_USERNAME}/ensure:latest"
    networks:
      - kafka-network
    depends_on:
      - "init-kafka"
    environment:
      - CLIENT_ID=3
      - NUM_EXHIBITIONS=$NUM_EXHIBITIONS
      - NUM_TRUE_ALARMS=$NUM_TRUE_ALARMS
      - NUM_FALSE_ALARMS=$NUM_FALSE_ALARMS
      - NUM_UNCAUGHT_BREACHES=$NUM_UNCAUGHT_BREACHES
    volumes:
      - ./results/ensure:/usr/kabis/result
