version: "3.8"

networks:
  bft-network:
    name: bft_benchmarks
    external: true
    driver: overlay
  kafka-network:
    name: kafka_benchmarks
    external: true
    driver: overlay

services:
  #Bft service replicas
  bft-1:
    image: "${DOCKERHUB_USERNAME}/kabis-service-replica:latest"
    networks:
      - bft-network
    environment:
      - ID=0
  bft-2:
    image: "${DOCKERHUB_USERNAME}/kabis-service-replica:latest"
    networks:
      - bft-network
    environment:
      - ID=1

  #First kafka replica
  zookeeper-1-1:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-network
    depends_on:
      - "bft-1"
      - "bft-2"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper-1-2:2888:3888,zookeeper-1-3:2888:3888,zookeeper-1-4:2888:3888
  zookeeper-1-2:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-network
    depends_on:
      - "bft-1"
      - "bft-2"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper-1-1:2888:3888,0.0.0.0:2888:3888,zookeeper-1-3:2888:3888,zookeeper-1-4:2888:3888

  kafka_1_1:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-network
    depends_on:
      - "zookeeper-1-1"
      - "zookeeper-1-2"
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_1:9092
  kafka_1_2:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-network
    depends_on:
      - "zookeeper-1-1"
      - "zookeeper-1-2"
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_2:9092

  #Second kafka replica
  zookeeper-2-1:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-network
    depends_on:
      - "bft-1"
      - "bft-2"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper-2-2:2888:3888
  zookeeper-2-2:
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-network
    depends_on:
      - "bft-1"
      - "bft-2"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper-2-1:2888:3888,0.0.0.0:2888:3888

  kafka_2_1:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-network
    depends_on:
      - "zookeeper-2-1"
      - "zookeeper-2-2"
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-2-1:2181,zookeeper-2-2:2181,zookeeper-2-3:2181,zookeeper-2-4:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_2_1:9092
  kafka_2_2:
    image: "bitnami/kafka:latest"
    networks:
      - kafka-network
    depends_on:
      - "zookeeper-2-1"
      - "zookeeper-2-2"
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-2-1:2181,zookeeper-2-2:2181,zookeeper-2-3:2181,zookeeper-2-4:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_2_2:9092

  #Clients
  safe-sense:
    image: "${DOCKERHUB_USERNAME}/safe-sense:latest"
    networks:
      - kafka-network
      - bft-network
    depends_on:
      - "kafka_1_1"
      - "kafka_1_2"
      - "kafka_2_1"
      - "kafka_2_2"
      - "bft-1"
      - "bft-2"
    environment:
      - CLIENT_ID=1001
      - NUM_EXHIBITIONS=$NUM_EXHIBITIONS
      - NUM_TRUE_ALARMS=$NUM_TRUE_ALARMS
      - NUM_FALSE_ALARMS=$NUM_FALSE_ALARMS
    volumes:
      - ./results/safe-sense:/usr/kabis/result
# safe-corp:
#   image: "${DOCKERHUB_USERNAME}/safe-corp:latest"
#   networks:
#     - kafka-network
#     - bft-network
#   depends_on:
#      - "kafka_1_1"
#      - "kafka_1_2"
#      - "kafka_2_1"
#      - "kafka_2_2"
#      - "bft-1"
#      - "bft-2"
#    environment:
#      - CLIENT_ID=1002
#      - NUM_EXHIBITIONS=$NUM_EXHIBITIONS
#      - NUM_TRUE_ALARMS=$NUM_TRUE_ALARMS
#      - NUM_FALSE_ALARMS=$NUM_FALSE_ALARMS
#      - NUM_UNCAUGHT_BREACHES=$NUM_UNCAUGHT_BREACHES
#    volumes:
#      - ./results/safe-corp:/usr/kabis/result
