version: "3.8"

services:
  #Bft service replicas
  bft-1:
    image: "${DOCKERHUB_USERNAME}/bft-sender-service-replica:latest"
    network_mode: host
    ports:
      - "11000:11000"
      - "11001:11001"
    environment:
      - ID=0
  bft-2:
    image: "${DOCKERHUB_USERNAME}/bft-sender-service-replica:latest"
    network_mode: host
    ports:
      - "11010:11010"
      - "11011:11011"
    environment:
      - ID=1
  bft-3:
    image: "${DOCKERHUB_USERNAME}/bft-sender-service-replica:latest"
    network_mode: host
    ports:
      - "11020:11020"
      - "11021:11021"
    environment:
      - ID=2

  #Clients
  sender-1:
    image: "${DOCKERHUB_USERNAME}/bft-sender:latest"
    network_mode: host
    depends_on:
      - "bft-1"
      - "bft-2"
      - "bft-3"
    ports:
      - "11100:11100"
    environment:
      - ID=1001
      - OPS_PER_SENDER=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/sender-1:/usr/kabis/result
  sender-2:
    image: "${DOCKERHUB_USERNAME}/bft-sender:latest"
    network_mode: host
    depends_on:
      - "bft-1"
      - "bft-2"
      - "bft-3"
    ports:
      - "11101:11101"
    environment:
      - ID=1002
      - OPS_PER_SENDER=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/sender-2:/usr/kabis/result
  sender-3:
    image: "${DOCKERHUB_USERNAME}/bft-sender:latest"
    network_mode: host
    depends_on:
      - "bft-1"
      - "bft-2"
      - "bft-3"
    ports:
      - "11102:11102"
    environment:
      - ID=1003
      - OPS_PER_SENDER=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/sender-4:/usr/kabis/result
