version: '2'

networks:
  bft:
    driver: bridge

services:
  #Bft service replicas
  bft-1:
    image: 'galaxarum/bft_service_replica:latest'
    networks:
      - bft
    environment:
      - ID=0
  bft-2:
    image: 'galaxarum/bft_service_replica:latest'
    networks:
      - bft
    environment:
      - ID=1
  bft-3:
    image: 'galaxarum/bft_service_replica:latest'
    networks:
      - bft
    environment:
      - ID=2
  bft-4:
    image: 'galaxarum/bft_service_replica:latest'
    networks:
      - bft
    environment:
      - ID=3

  #Clients
  sender-1:
    image: 'galaxarum/bft_sender:latest'
    networks:
      - bft
    depends_on:
      - 'bft-1'
      - 'bft-2'
      - 'bft-3'
      - 'bft-4'
    environment:
      - ID=1001
      - OPS_PER_SENDER=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/sender-1:/usr/kabis/result
  sender-2:
    image: 'galaxarum/bft_sender:latest'
    networks:
      - bft
    depends_on:
      - 'bft-1'
      - 'bft-2'
      - 'bft-3'
      - 'bft-4'
    environment:
      - ID=1002
      - OPS_PER_SENDER=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/sender-2:/usr/kabis/result
  sender-3:
    image: 'galaxarum/bft_sender:latest'
    networks:
      - bft
    depends_on:
      - 'bft-1'
      - 'bft-2'
      - 'bft-3'
      - 'bft-4'
    environment:
      - ID=1003
      - OPS_PER_SENDER=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/sender-4:/usr/kabis/result
  receiver-1:
    image: 'galaxarum/bft_receiver:latest'
    networks:
      - bft
    depends_on:
      - 'bft-1'
      - 'bft-2'
      - 'bft-3'
      - 'bft-4'
    environment:
      - ID=1004
      - OPS_PER_SENDER=$SENDER_OPS
      - NUM_SENDERS=3
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/receiver-1:/usr/kabis/result