version: '2'

networks:
  kafka-net:
    driver: bridge

services:

  #First kafka replica
  zookeeper-1-1:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper-1-2:2888:3888,zookeeper-1-3:2888:3888,zookeeper-1-4:2888:3888
  zookeeper-1-2:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper-1-1:2888:3888,0.0.0.0:2888:3888,zookeeper-1-3:2888:3888,zookeeper-1-4:2888:3888
  zookeeper-1-3:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper-1-1:2888:3888,zookeeper-1-2:2888:3888,0.0.0.0:2888:3888,zookeeper-1-4:2888:3888
  zookeeper-1-4:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=4
      - ZOO_SERVERS=zookeeper-1-1:2888:3888,zookeeper-1-2:2888:3888,zookeeper-1-3:2888:3888,0.0.0.0:2888:3888
  kafka_1_1:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    depends_on:
      - 'zookeeper-1-1'
      - 'zookeeper-1-2'
      - 'zookeeper-1-3'
      - 'zookeeper-1-4'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_1:9092
  kafka_1_2:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    depends_on:
      - 'zookeeper-1-1'
      - 'zookeeper-1-2'
      - 'zookeeper-1-3'
      - 'zookeeper-1-4'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_2:9092
  kafka_1_3:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    depends_on:
      - 'zookeeper-1-1'
      - 'zookeeper-1-2'
      - 'zookeeper-1-3'
      - 'zookeeper-1-4'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_3:9092
  kafka_1_4:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    depends_on:
      - 'zookeeper-1-1'
      - 'zookeeper-1-2'
      - 'zookeeper-1-3'
      - 'zookeeper-1-4'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1-1:2181,zookeeper-1-2:2181,zookeeper-1-3:2181,zookeeper-1-4:2181
      - KAFKA_BROKER_ID=4
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1_4:9092

  #Clients
  sender-1:
    image: 'flavioriz/kafka-sender:latest'
    networks:
      - kafka-net
    depends_on:
      - 'kafka_1_1'
      - 'kafka_1_2'
      - 'kafka_1_3'
      - 'kafka_1_4'
    environment:
      - ID=1001
      - NUM_OPERATIONS=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/sender-1:/usr/kabis/result
  sender-2:
    image: 'flavioriz/kafka-sender:latest'
    networks:
      - kafka-net
    depends_on:
      - 'kafka_1_1'
      - 'kafka_1_2'
      - 'kafka_1_3'
      - 'kafka_1_4'
    environment:
      - ID=1002
      - NUM_OPERATIONS=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/sender-2:/usr/kabis/result
  sender-3:
    image: 'flavioriz/kafka-sender:latest'
    networks:
      - kafka-net
    depends_on:
      - 'kafka_1_1'
      - 'kafka_1_2'
      - 'kafka_1_3'
      - 'kafka_1_4'
    environment:
      - ID=1003
      - NUM_OPERATIONS=$SENDER_OPS
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/sender-3:/usr/kabis/result
  receiver-1:
    image: 'flavioriz/kafka-receiver:latest'
    networks:
      - kafka-net
    depends_on:
      - 'kafka_1_1'
      - 'kafka_1_2'
      - 'kafka_1_3'
      - 'kafka_1_4'
    environment:
      - ID=1004
      - OPS_PER_SENDER=$SENDER_OPS
      - NUM_SENDERS=3
      - PAYLOAD_SIZE=$PAYLOAD
    volumes:
      - ./results/receiver-1:/usr/kabis/result